//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Assets_Script_Frame_UiControlContainerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Assets.Script.Frame.UiControlContainer), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("RegistObject", RegistObject);
		L.RegFunction("UnRegistObject", UnRegistObject);
		L.RegFunction("GetObject", GetObject);
		L.RegFunction("RegistButton", RegistButton);
		L.RegFunction("UnRegistButton", UnRegistButton);
		L.RegFunction("GetButton", GetButton);
		L.RegFunction("RegistText", RegistText);
		L.RegFunction("UnRegistText", UnRegistText);
		L.RegFunction("GetText", GetText);
		L.RegFunction("RegistSlider", RegistSlider);
		L.RegFunction("UnRegistSlider", UnRegistSlider);
		L.RegFunction("GetSlider", GetSlider);
		L.RegFunction("RegistImage", RegistImage);
		L.RegFunction("UnRegistImage", UnRegistImage);
		L.RegFunction("GetImage", GetImage);
		L.RegFunction("RegistInputField", RegistInputField);
		L.RegFunction("UnRegistInputField", UnRegistInputField);
		L.RegFunction("GetInputField", GetInputField);
		L.RegFunction("RegistPanelBase", RegistPanelBase);
		L.RegFunction("UnRegistPanelBase", UnRegistPanelBase);
		L.RegFunction("GetPanelBase", GetPanelBase);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("panelbases", get_panelbases, set_panelbases);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 3, typeof(UnityEngine.GameObject));
			bool o = obj.RegistObject(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.UnRegistObject(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.GameObject o = obj.GetObject(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistButton(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Button arg1 = (UnityEngine.UI.Button)ToLua.CheckUnityObject(L, 3, typeof(UnityEngine.UI.Button));
			bool o = obj.RegistButton(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistButton(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.UnRegistButton(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetButton(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Button o = obj.GetButton(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Text arg1 = (UnityEngine.UI.Text)ToLua.CheckUnityObject(L, 3, typeof(UnityEngine.UI.Text));
			bool o = obj.RegistText(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.UnRegistText(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Text o = obj.GetText(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistSlider(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Slider arg1 = (UnityEngine.UI.Slider)ToLua.CheckUnityObject(L, 3, typeof(UnityEngine.UI.Slider));
			bool o = obj.RegistSlider(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistSlider(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.UnRegistSlider(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSlider(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Slider o = obj.GetSlider(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Image arg1 = (UnityEngine.UI.Image)ToLua.CheckUnityObject(L, 3, typeof(UnityEngine.UI.Image));
			bool o = obj.RegistImage(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.UnRegistImage(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Image o = obj.GetImage(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistInputField(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.InputField arg1 = (UnityEngine.UI.InputField)ToLua.CheckUnityObject(L, 3, typeof(UnityEngine.UI.InputField));
			bool o = obj.RegistInputField(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistInputField(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.UnRegistInputField(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInputField(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.InputField o = obj.GetInputField(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistPanelBase(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			Assets.Script.Frame.PanelBase arg1 = (Assets.Script.Frame.PanelBase)ToLua.CheckUnityObject(L, 3, typeof(Assets.Script.Frame.PanelBase));
			bool o = obj.RegistPanelBase(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistPanelBase(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.UnRegistPanelBase(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPanelBase(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.UiControlContainer));
			string arg0 = ToLua.CheckString(L, 2);
			Assets.Script.Frame.PanelBase o = obj.GetPanelBase(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_panelbases(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)o;
			System.Collections.Generic.Dictionary<string,Assets.Script.Frame.PanelBase> ret = obj.panelbases;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index panelbases on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_panelbases(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Script.Frame.UiControlContainer obj = (Assets.Script.Frame.UiControlContainer)o;
			System.Collections.Generic.Dictionary<string,Assets.Script.Frame.PanelBase> arg0 = (System.Collections.Generic.Dictionary<string,Assets.Script.Frame.PanelBase>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<string,Assets.Script.Frame.PanelBase>));
			obj.panelbases = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index panelbases on a nil value" : e.Message);
		}
	}
}

