//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Assets_Script_Frame_PanelBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Assets.Script.Frame.PanelBase), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetButton", GetButton);
		L.RegFunction("GetText", GetText);
		L.RegFunction("GetImage", GetImage);
		L.RegFunction("GetSubPanel", GetSubPanel);
		L.RegFunction("Init", Init);
		L.RegFunction("Show", Show);
		L.RegFunction("Hide", Hide);
		L.RegFunction("Refresh", Refresh);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("controls", get_controls, null);
		L.RegVar("subPanels", get_subPanels, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetButton(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.PanelBase obj = (Assets.Script.Frame.PanelBase)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.PanelBase));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Button o = obj.GetButton(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.PanelBase obj = (Assets.Script.Frame.PanelBase)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.PanelBase));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Text o = obj.GetText(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.PanelBase obj = (Assets.Script.Frame.PanelBase)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.PanelBase));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.UI.Image o = obj.GetImage(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSubPanel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.PanelBase obj = (Assets.Script.Frame.PanelBase)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.PanelBase));
			string arg0 = ToLua.CheckString(L, 2);
			Assets.Script.Frame.PanelBase o = obj.GetSubPanel(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Assets.Script.Frame.PanelBase obj = (Assets.Script.Frame.PanelBase)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.PanelBase));
			obj.Init();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Show(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Assets.Script.Frame.PanelBase obj = (Assets.Script.Frame.PanelBase)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.PanelBase));
			obj.Show();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Hide(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Assets.Script.Frame.PanelBase obj = (Assets.Script.Frame.PanelBase)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.PanelBase));
			obj.Hide();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Refresh(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Assets.Script.Frame.PanelBase obj = (Assets.Script.Frame.PanelBase)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.PanelBase));
			obj.Refresh();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_controls(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Script.Frame.PanelBase obj = (Assets.Script.Frame.PanelBase)o;
			Assets.Script.Frame.UiControlContainer ret = obj.controls;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index controls on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_subPanels(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Script.Frame.PanelBase obj = (Assets.Script.Frame.PanelBase)o;
			Assets.Script.Frame.PanelBase[] ret = obj.subPanels;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index subPanels on a nil value" : e.Message);
		}
	}
}

