//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Assets_Script_Frame_EventSystemWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Assets.Script.Frame.EventSystem), typeof(Assets.Script.Frame.Singleton<Assets.Script.Frame.EventSystem>));
		L.RegFunction("Reset", Reset);
		L.RegFunction("RegistReceiver", RegistReceiver);
		L.RegFunction("UnRegistReceiver", UnRegistReceiver);
		L.RegFunction("RealRegistReceiver", RealRegistReceiver);
		L.RegFunction("RealUnregistEventReceiver", RealUnregistEventReceiver);
		L.RegFunction("RealSendEvent", RealSendEvent);
		L.RegFunction("Update", Update);
		L.RegFunction("postEvent", postEvent);
		L.RegFunction("sendEvent", sendEvent);
		L.RegFunction("New", _CreateAssets_Script_Frame_EventSystem);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("evtQueue", get_evtQueue, set_evtQueue);
		L.RegVar("receivers", get_receivers, set_receivers);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAssets_Script_Frame_EventSystem(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Assets.Script.Frame.EventSystem obj = new Assets.Script.Frame.EventSystem();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Assets.Script.Frame.EventSystem.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Reset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.EventSystem));
			obj.Reset();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistReceiver(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.EventSystem));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Assets.Script.Frame.IEventReceiver arg1 = (Assets.Script.Frame.IEventReceiver)ToLua.CheckObject(L, 3, typeof(Assets.Script.Frame.IEventReceiver));
			obj.RegistReceiver(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistReceiver(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.EventSystem));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Assets.Script.Frame.IEventReceiver arg1 = (Assets.Script.Frame.IEventReceiver)ToLua.CheckObject(L, 3, typeof(Assets.Script.Frame.IEventReceiver));
			obj.UnRegistReceiver(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RealRegistReceiver(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.EventSystem));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Assets.Script.Frame.IEventReceiver arg1 = (Assets.Script.Frame.IEventReceiver)ToLua.CheckObject(L, 3, typeof(Assets.Script.Frame.IEventReceiver));
			obj.RealRegistReceiver(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RealUnregistEventReceiver(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.EventSystem));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Assets.Script.Frame.IEventReceiver arg1 = (Assets.Script.Frame.IEventReceiver)ToLua.CheckObject(L, 3, typeof(Assets.Script.Frame.IEventReceiver));
			obj.RealUnregistEventReceiver(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RealSendEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.EventSystem));
			Assets.Script.Frame.IEvent arg0 = (Assets.Script.Frame.IEvent)ToLua.CheckObject(L, 2, typeof(Assets.Script.Frame.IEvent));
			obj.RealSendEvent(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.EventSystem));
			obj.Update();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int postEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.EventSystem));
			Assets.Script.Frame.IEvent arg0 = (Assets.Script.Frame.IEvent)ToLua.CheckObject(L, 2, typeof(Assets.Script.Frame.IEvent));
			obj.postEvent(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int sendEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)ToLua.CheckObject(L, 1, typeof(Assets.Script.Frame.EventSystem));
			Assets.Script.Frame.IEvent arg0 = (Assets.Script.Frame.IEvent)ToLua.CheckObject(L, 2, typeof(Assets.Script.Frame.IEvent));
			obj.sendEvent(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_evtQueue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)o;
			System.Collections.Generic.Queue<Assets.Script.Frame.IEvent> ret = obj.evtQueue;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index evtQueue on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_receivers(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)o;
			System.Collections.Generic.Dictionary<int,System.Collections.Generic.List<Assets.Script.Frame.IEventReceiver>> ret = obj.receivers;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index receivers on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_evtQueue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)o;
			System.Collections.Generic.Queue<Assets.Script.Frame.IEvent> arg0 = (System.Collections.Generic.Queue<Assets.Script.Frame.IEvent>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Queue<Assets.Script.Frame.IEvent>));
			obj.evtQueue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index evtQueue on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_receivers(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Assets.Script.Frame.EventSystem obj = (Assets.Script.Frame.EventSystem)o;
			System.Collections.Generic.Dictionary<int,System.Collections.Generic.List<Assets.Script.Frame.IEventReceiver>> arg0 = (System.Collections.Generic.Dictionary<int,System.Collections.Generic.List<Assets.Script.Frame.IEventReceiver>>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<int,System.Collections.Generic.List<Assets.Script.Frame.IEventReceiver>>));
			obj.receivers = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index receivers on a nil value" : e.Message);
		}
	}
}

