// Code generated by protoc-gen-go.
// source: all.proto
// DO NOT EDIT!

/*
Package packs is a generated protocol buffer package.

It is generated from these files:
	all.proto

It has these top-level messages:
	UserInfo
	ReqRegist
	UserRegist
	ReqLogon
	UserLogon
	ReqLogout
	UserLogout
	ReqChangeTeamIconFrame
	TeamIconFrameChanged
	ReqUserAddCoin
	UserAddCoin
	ReqChangeUsername
	ChangeUsername
	HeroInfo
*/
package packs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	Id            int32       `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Username      string      `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Coin          int32       `protobuf:"varint,3,opt,name=Coin" json:"Coin,omitempty"`
	Diamond       int32       `protobuf:"varint,4,opt,name=Diamond" json:"Diamond,omitempty"`
	Vigour        int32       `protobuf:"varint,5,opt,name=Vigour" json:"Vigour,omitempty"`
	VipLevel      int32       `protobuf:"varint,6,opt,name=VipLevel" json:"VipLevel,omitempty"`
	TeamLevel     int32       `protobuf:"varint,7,opt,name=TeamLevel" json:"TeamLevel,omitempty"`
	TeamExp       int32       `protobuf:"varint,8,opt,name=TeamExp" json:"TeamExp,omitempty"`
	TeamIcon      int32       `protobuf:"varint,9,opt,name=TeamIcon" json:"TeamIcon,omitempty"`
	TeamIconFrame int32       `protobuf:"varint,10,opt,name=TeamIconFrame" json:"TeamIconFrame,omitempty"`
	BattlePower   int32       `protobuf:"varint,11,opt,name=BattlePower" json:"BattlePower,omitempty"`
	TeamTimes     int32       `protobuf:"varint,12,opt,name=TeamTimes" json:"TeamTimes,omitempty"`
	HeroList      []*HeroInfo `protobuf:"bytes,13,rep,name=HeroList" json:"HeroList,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetCoin() int32 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *UserInfo) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *UserInfo) GetVigour() int32 {
	if m != nil {
		return m.Vigour
	}
	return 0
}

func (m *UserInfo) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

func (m *UserInfo) GetTeamLevel() int32 {
	if m != nil {
		return m.TeamLevel
	}
	return 0
}

func (m *UserInfo) GetTeamExp() int32 {
	if m != nil {
		return m.TeamExp
	}
	return 0
}

func (m *UserInfo) GetTeamIcon() int32 {
	if m != nil {
		return m.TeamIcon
	}
	return 0
}

func (m *UserInfo) GetTeamIconFrame() int32 {
	if m != nil {
		return m.TeamIconFrame
	}
	return 0
}

func (m *UserInfo) GetBattlePower() int32 {
	if m != nil {
		return m.BattlePower
	}
	return 0
}

func (m *UserInfo) GetTeamTimes() int32 {
	if m != nil {
		return m.TeamTimes
	}
	return 0
}

func (m *UserInfo) GetHeroList() []*HeroInfo {
	if m != nil {
		return m.HeroList
	}
	return nil
}

type ReqRegist struct {
	Username string `protobuf:"bytes,1,opt,name=Username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *ReqRegist) Reset()                    { *m = ReqRegist{} }
func (m *ReqRegist) String() string            { return proto.CompactTextString(m) }
func (*ReqRegist) ProtoMessage()               {}
func (*ReqRegist) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReqRegist) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqRegist) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserRegist struct {
	ErrorCode int32     `protobuf:"varint,1,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
	UserInfo  *UserInfo `protobuf:"bytes,2,opt,name=UserInfo" json:"UserInfo,omitempty"`
}

func (m *UserRegist) Reset()                    { *m = UserRegist{} }
func (m *UserRegist) String() string            { return proto.CompactTextString(m) }
func (*UserRegist) ProtoMessage()               {}
func (*UserRegist) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserRegist) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *UserRegist) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type ReqLogon struct {
	Username string `protobuf:"bytes,1,opt,name=Username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *ReqLogon) Reset()                    { *m = ReqLogon{} }
func (m *ReqLogon) String() string            { return proto.CompactTextString(m) }
func (*ReqLogon) ProtoMessage()               {}
func (*ReqLogon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReqLogon) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqLogon) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLogon struct {
	ErrorCode int32     `protobuf:"varint,1,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
	UserInfo  *UserInfo `protobuf:"bytes,2,opt,name=UserInfo" json:"UserInfo,omitempty"`
}

func (m *UserLogon) Reset()                    { *m = UserLogon{} }
func (m *UserLogon) String() string            { return proto.CompactTextString(m) }
func (*UserLogon) ProtoMessage()               {}
func (*UserLogon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserLogon) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *UserLogon) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type ReqLogout struct {
	UserId int32 `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
}

func (m *ReqLogout) Reset()                    { *m = ReqLogout{} }
func (m *ReqLogout) String() string            { return proto.CompactTextString(m) }
func (*ReqLogout) ProtoMessage()               {}
func (*ReqLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReqLogout) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserLogout struct {
	UserId int32 `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
}

func (m *UserLogout) Reset()                    { *m = UserLogout{} }
func (m *UserLogout) String() string            { return proto.CompactTextString(m) }
func (*UserLogout) ProtoMessage()               {}
func (*UserLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UserLogout) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ReqChangeTeamIconFrame struct {
	Userid        int32 `protobuf:"varint,1,opt,name=Userid" json:"Userid,omitempty"`
	TeamIconFrame int32 `protobuf:"varint,2,opt,name=TeamIconFrame" json:"TeamIconFrame,omitempty"`
}

func (m *ReqChangeTeamIconFrame) Reset()                    { *m = ReqChangeTeamIconFrame{} }
func (m *ReqChangeTeamIconFrame) String() string            { return proto.CompactTextString(m) }
func (*ReqChangeTeamIconFrame) ProtoMessage()               {}
func (*ReqChangeTeamIconFrame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReqChangeTeamIconFrame) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *ReqChangeTeamIconFrame) GetTeamIconFrame() int32 {
	if m != nil {
		return m.TeamIconFrame
	}
	return 0
}

type TeamIconFrameChanged struct {
	Userid       int32 `protobuf:"varint,1,opt,name=Userid" json:"Userid,omitempty"`
	TeamIconFram int32 `protobuf:"varint,2,opt,name=TeamIconFram" json:"TeamIconFram,omitempty"`
}

func (m *TeamIconFrameChanged) Reset()                    { *m = TeamIconFrameChanged{} }
func (m *TeamIconFrameChanged) String() string            { return proto.CompactTextString(m) }
func (*TeamIconFrameChanged) ProtoMessage()               {}
func (*TeamIconFrameChanged) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TeamIconFrameChanged) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *TeamIconFrameChanged) GetTeamIconFram() int32 {
	if m != nil {
		return m.TeamIconFram
	}
	return 0
}

type ReqUserAddCoin struct {
	Userid int32 `protobuf:"varint,1,opt,name=Userid" json:"Userid,omitempty"`
}

func (m *ReqUserAddCoin) Reset()                    { *m = ReqUserAddCoin{} }
func (m *ReqUserAddCoin) String() string            { return proto.CompactTextString(m) }
func (*ReqUserAddCoin) ProtoMessage()               {}
func (*ReqUserAddCoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ReqUserAddCoin) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

type UserAddCoin struct {
	Userid   int32     `protobuf:"varint,1,opt,name=Userid" json:"Userid,omitempty"`
	UserInfo *UserInfo `protobuf:"bytes,2,opt,name=UserInfo" json:"UserInfo,omitempty"`
	Coin     int32     `protobuf:"varint,3,opt,name=Coin" json:"Coin,omitempty"`
	Diamond  int32     `protobuf:"varint,4,opt,name=Diamond" json:"Diamond,omitempty"`
	VipLevel int32     `protobuf:"varint,6,opt,name=VipLevel" json:"VipLevel,omitempty"`
}

func (m *UserAddCoin) Reset()                    { *m = UserAddCoin{} }
func (m *UserAddCoin) String() string            { return proto.CompactTextString(m) }
func (*UserAddCoin) ProtoMessage()               {}
func (*UserAddCoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UserAddCoin) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *UserAddCoin) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *UserAddCoin) GetCoin() int32 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *UserAddCoin) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *UserAddCoin) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

type ReqChangeUsername struct {
	Userid   int32  `protobuf:"varint,1,opt,name=Userid" json:"Userid,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
}

func (m *ReqChangeUsername) Reset()                    { *m = ReqChangeUsername{} }
func (m *ReqChangeUsername) String() string            { return proto.CompactTextString(m) }
func (*ReqChangeUsername) ProtoMessage()               {}
func (*ReqChangeUsername) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ReqChangeUsername) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *ReqChangeUsername) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ChangeUsername struct {
	Userid   int32  `protobuf:"varint,1,opt,name=Userid" json:"Userid,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
}

func (m *ChangeUsername) Reset()                    { *m = ChangeUsername{} }
func (m *ChangeUsername) String() string            { return proto.CompactTextString(m) }
func (*ChangeUsername) ProtoMessage()               {}
func (*ChangeUsername) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ChangeUsername) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *ChangeUsername) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type HeroInfo struct {
	Id      int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Level   int32 `protobuf:"varint,2,opt,name=Level" json:"Level,omitempty"`
	Star    int32 `protobuf:"varint,3,opt,name=Star" json:"Star,omitempty"`
	Quality int32 `protobuf:"varint,5,opt,name=Quality" json:"Quality,omitempty"`
}

func (m *HeroInfo) Reset()                    { *m = HeroInfo{} }
func (m *HeroInfo) String() string            { return proto.CompactTextString(m) }
func (*HeroInfo) ProtoMessage()               {}
func (*HeroInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *HeroInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HeroInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *HeroInfo) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *HeroInfo) GetQuality() int32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "packs.UserInfo")
	proto.RegisterType((*ReqRegist)(nil), "packs.ReqRegist")
	proto.RegisterType((*UserRegist)(nil), "packs.UserRegist")
	proto.RegisterType((*ReqLogon)(nil), "packs.ReqLogon")
	proto.RegisterType((*UserLogon)(nil), "packs.UserLogon")
	proto.RegisterType((*ReqLogout)(nil), "packs.ReqLogout")
	proto.RegisterType((*UserLogout)(nil), "packs.UserLogout")
	proto.RegisterType((*ReqChangeTeamIconFrame)(nil), "packs.ReqChangeTeamIconFrame")
	proto.RegisterType((*TeamIconFrameChanged)(nil), "packs.TeamIconFrameChanged")
	proto.RegisterType((*ReqUserAddCoin)(nil), "packs.ReqUserAddCoin")
	proto.RegisterType((*UserAddCoin)(nil), "packs.UserAddCoin")
	proto.RegisterType((*ReqChangeUsername)(nil), "packs.ReqChangeUsername")
	proto.RegisterType((*ChangeUsername)(nil), "packs.ChangeUsername")
	proto.RegisterType((*HeroInfo)(nil), "packs.HeroInfo")
}

func init() { proto.RegisterFile("all.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0xb2, 0xb5, 0x4b, 0x6e, 0xb7, 0x22, 0xac, 0x69, 0xb2, 0xa6, 0x3d, 0x54, 0x66, 0x0f,
	0x95, 0x90, 0xfa, 0x00, 0x5f, 0xc0, 0xba, 0x01, 0x95, 0xfa, 0x30, 0xcc, 0x28, 0x6f, 0x48, 0x66,
	0x36, 0xc5, 0x22, 0x8d, 0x5b, 0x27, 0x65, 0xf0, 0x2f, 0xfc, 0x2b, 0xe8, 0xda, 0x71, 0xb2, 0xc0,
	0x3a, 0x18, 0xea, 0x9b, 0xcf, 0xb9, 0x27, 0xc7, 0x37, 0xc7, 0xd7, 0x86, 0x54, 0x64, 0xd9, 0x68,
	0x69, 0x4d, 0x69, 0x48, 0x67, 0x29, 0xae, 0xbf, 0x14, 0xec, 0x67, 0x0c, 0xc9, 0xbb, 0x42, 0xd9,
	0x49, 0xfe, 0xc9, 0x90, 0x3e, 0xc4, 0x13, 0x49, 0xa3, 0x41, 0x34, 0xec, 0xf0, 0x78, 0x22, 0xc9,
	0xb1, 0xaf, 0xe5, 0x62, 0xa1, 0x68, 0x3c, 0x88, 0x86, 0x29, 0xaf, 0x31, 0x21, 0xb0, 0x3b, 0x36,
	0x3a, 0xa7, 0x3b, 0x4e, 0xed, 0xd6, 0x84, 0xc2, 0xde, 0xb9, 0x16, 0x0b, 0x93, 0x4b, 0xba, 0xeb,
	0xe8, 0x00, 0xc9, 0x11, 0x74, 0x67, 0x7a, 0x6e, 0xd6, 0x96, 0x76, 0x5c, 0xa1, 0x42, 0xb8, 0xc3,
	0x4c, 0x2f, 0xa7, 0xea, 0xab, 0xca, 0x68, 0xd7, 0x55, 0x6a, 0x4c, 0x4e, 0x20, 0xbd, 0x52, 0x62,
	0xe1, 0x8b, 0x7b, 0xae, 0xd8, 0x10, 0xb8, 0x17, 0x82, 0x8b, 0x6f, 0x4b, 0x9a, 0xf8, 0xbd, 0x2a,
	0x88, 0x9e, 0xb8, 0x9c, 0x5c, 0x9b, 0x9c, 0xa6, 0xde, 0x33, 0x60, 0x72, 0x0a, 0x07, 0x61, 0xfd,
	0xd2, 0xe2, 0x6f, 0x81, 0x13, 0xb4, 0x49, 0x32, 0x80, 0xde, 0x99, 0x28, 0xcb, 0x4c, 0x5d, 0x9a,
	0x1b, 0x65, 0x69, 0xcf, 0x69, 0x6e, 0x53, 0xa1, 0xb7, 0x2b, 0xbd, 0x50, 0x05, 0xdd, 0x6f, 0x7a,
	0x73, 0x04, 0x79, 0x0a, 0xc9, 0x6b, 0x65, 0xcd, 0x54, 0x17, 0x25, 0x3d, 0x18, 0xec, 0x0c, 0x7b,
	0xcf, 0x1e, 0x8d, 0x5c, 0xdc, 0x23, 0xa4, 0x31, 0x6a, 0x5e, 0x0b, 0xd8, 0x18, 0x52, 0xae, 0x56,
	0x5c, 0xcd, 0x75, 0x51, 0xb6, 0x12, 0x8f, 0x7e, 0x4b, 0xfc, 0x18, 0x92, 0x4b, 0x51, 0x14, 0x37,
	0xc6, 0xca, 0x70, 0x1a, 0x01, 0xb3, 0xf7, 0x00, 0xa8, 0xab, 0x5c, 0x4e, 0x20, 0xbd, 0xb0, 0xd6,
	0xd8, 0xb1, 0x91, 0xaa, 0x3a, 0xce, 0x86, 0xc0, 0xee, 0xc2, 0x89, 0x3b, 0x9f, 0xa6, 0xbb, 0x40,
	0xf3, 0x5a, 0xc0, 0xce, 0x20, 0xe1, 0x6a, 0x35, 0x35, 0x73, 0x93, 0xff, 0x77, 0x73, 0x33, 0x48,
	0x51, 0xe7, 0x4d, 0xb6, 0xd8, 0xdb, 0x13, 0x97, 0x1c, 0xda, 0xae, 0x4b, 0x9c, 0x30, 0x57, 0x08,
	0xf3, 0x5b, 0x21, 0x76, 0xea, 0x93, 0xf9, 0x8b, 0x6a, 0x06, 0x47, 0x5c, 0xad, 0xc6, 0x9f, 0x45,
	0x3e, 0x57, 0xed, 0x59, 0xa8, 0xbe, 0xd0, 0xad, 0x2f, 0xb4, 0xfc, 0x73, 0x92, 0xe2, 0x3b, 0x26,
	0x89, 0x71, 0x38, 0x6c, 0x11, 0x7e, 0x07, 0xb9, 0xd1, 0x95, 0xc1, 0xfe, 0x6d, 0x7d, 0x65, 0xda,
	0xe2, 0xd8, 0x10, 0xfa, 0x5c, 0xad, 0xf0, 0x83, 0x17, 0x52, 0xba, 0x7b, 0xb7, 0xc1, 0x8d, 0xfd,
	0x88, 0xa0, 0xf7, 0x0f, 0xba, 0x07, 0xa5, 0xfe, 0xc0, 0x8b, 0x7f, 0xcf, 0x05, 0x67, 0xaf, 0xe0,
	0x71, 0x1d, 0x7a, 0x3d, 0x48, 0x9b, 0x7a, 0xbc, 0xe7, 0x2d, 0x62, 0xe7, 0xd0, 0xdf, 0x82, 0xcb,
	0x07, 0x7f, 0x6b, 0xef, 0x7c, 0x09, 0x0f, 0xa1, 0xe3, 0xff, 0xc1, 0x1f, 0x88, 0x07, 0x18, 0xc5,
	0xdb, 0x52, 0xd8, 0x10, 0x05, 0xae, 0x31, 0x8a, 0x37, 0x6b, 0x91, 0xe9, 0xf2, 0x7b, 0xf5, 0xd4,
	0x05, 0xf8, 0xb1, 0xeb, 0x1e, 0xde, 0xe7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x71, 0xb4, 0x3d,
	0x92, 0x85, 0x05, 0x00, 0x00,
}
